name: Build & Deploy Windows Client

on:
  workflow_dispatch: {}

env:
  BUILD_FULL_NAME: "${{ vars.CLIENT_BUILD_NAME }}"
  BUILD_TARGET: StandaloneWindows

jobs:
    buildAndDeployClient:
      name: Build & deploy
      runs-on: ubuntu-latest
      steps:
        
        # Checkouts the current repository
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 1
        
        # Builds the Windows client using a given license
        - name: Build
          id: build
          uses: game-ci/unity-builder@v2
          env:
            UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          with:
            buildName: "${{ env.BUILD_FULL_NAME }}"
            targetPlatform: ${{ env.BUILD_TARGET }}
            versioning: Tag
            buildMethod: Digi.EditorTools.BuildScript.Build
            customParameters: -productType Client 
                              -environmentType Development
                              -serverType Hosted

        - name: Print build version
          run: |
            echo "${{ steps.build.outputs.buildVersion }}"
        
        - name: Check build success
          if: ${{ steps.build.outputs.buildVersion == '' }}
          run: |
            echo "Aborting the job..."
            exit 1
        
        - name: Post build placeholder
          run: |
            echo "The job continues..."